---

- name: Ensure Q3server base path exists
  file:
    path: "{{ q3server_base_data_path }}"
    state: directory
    mode: 0750
    owner: root
    group: root

- name: Ensure Q3server config path exists
  file:
    path: "{{ q3server_config_path }}"
    state: directory
    mode: 0750
    owner: root
    group: root

- name: Check existence of Nginx-proxy network in Docker
  shell:
    cmd: "docker network ls -q --filter='name=^{{ nginx_docker_network }}$'"
  register: nginx_result_docker_network
  changed_when: false

- name: Fail if docker network not defined
  fail:
    msg: >-
      You need to define a docker network (`{{ nginx_docker_network }}`) for using this service.
  when: nginx_result_docker_network.stdout == ''