---

- name: Ensure systemd reloaded
  service:
    daemon_reload: yes

- name: Ensure Q3server services stopped
  service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ q3server_services_list }}"

- name: Ensure Q3server services started
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ q3server_services_list }}"